version: "3"

volumes:
  postgres:

services:
  db:
    image: postgres:10.2-alpine
    ports:
      - 5432:5432
  api:
    build: .
    environment:
      DEBUG: 1
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/code
